services:
#    ubicacion.example:
#        class: Matudelatower\UbicacionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    ubicacion_bundle.configurator:
        class: Matudelatower\UbicacionBundle\Services\UbicacionConfigurator
        arguments: [%matudelatower.ubicacionbundle.template%]
