localidad_index:
    path:     /
    defaults: { _controller: "UbicacionBundle:Localidad:index" }
    methods:  GET

localidad_show:
    path:     /{id}/show
    defaults: { _controller: "UbicacionBundle:Localidad:show" }
    methods:  GET

localidad_new:
    path:     /new
    defaults: { _controller: "UbicacionBundle:Localidad:new" }
    methods:  [GET, POST]

localidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbicacionBundle:Localidad:edit" }
    methods:  [GET, POST]

localidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbicacionBundle:Localidad:delete" }
    methods:  DELETE
